services:
   app:
     image: 'generate-service:latest'
     build:
       context: .
     ports:
       - 7080:7080
     container_name: generateNumService
     depends_on:
       - redis1
   redis1:
      image: "redis:latest"
      ports:
       - 6379:6379