services:
   app:
     image: 'generate-service:latest'
     build:
       context: .
     ports:
       - 9080:9080
     container_name: generateService
     links:
      - redis
   redis:
     image: redis
     ports:
       - "6379:6379"
     environment:
       - REDIS_PASSWORD=my-password
       - REDIS_PORT=6379
       - REDIS_DATABASES=16